### ISSUE TITLE
Trip Sequence Variable TSEG is not populated

### ISSUE THREAD

**Issue by YanmeiOu** [RSGInc/DaySim#123]
Variable TSEG is 0 for about 90% of trips in SACOG's recent model run. It's hard to check trip chaining without TSEG properly filled.

**Comment by mabcal** [comment]
Hi, Yanmei

That is not happening when I run the latest code the test version of your data, and we have never seen it happen in any other runs.

Are you sure you’re reading the trip file correctly?  The variable TSVID, which is right after TSEG on the file, will always be 0 in application mode, but TSEG will always be >0.

Mark

**Comment by YanmeiOu** [comment]
Thanks Mark.

Just checked the direct output trip table from model run. You’re right that TSEG is populated. We mostly check the DBF table converted from TSV file using Cube script. I’ll double check our Cube script to see what’s going on.

Yanmei
