### ISSUE TITLE
Option to write paid rideshare trip number of passengers (1, 2 or 3+) on output trip records

### ISSUE THREAD

**Issue by mabcal** [RSGInc/DaySim#152]
This option is added so that Paid rideshare trips have an occupancy code on the output trip records.  To do this, the use of "mode" is expanded on the output trip record, so instead of 9, the augmented mode codes are...
 91 = paid rideshare, 1 passenger (not including driver for non-AV TNC)
 92 = paid rideshare, 2 passengers (not including driver for non-AV TNC)
 93 = paid rideshare, 3+ passengers (not including driver for non-AV TNC)

This option works the same way whether the mode is AV-based or not, but if it is non-AV-based, then the true occupancy is the number of passengers plus 1 (the TNC driver). 

The option is turned on by setting..... 
PaidRideshare_OutputNumberOfPassengersOnTripRecord = true

If it is turned on, DaySim expects the following 12 inputs below.  For each of 4 tour purposes, there is the share of TNC trips that are 1 passenger and 2 passenger.  The share that are 3+ passenger is then calculated as 1 - those 2 shares.  The other input is the average number of passengers for 3+ passenger trips.  The representative values below were obtained by analyzing the TNC trips from the SANDAG survey and from the NHTS Bay Area trips. 

PaidRideshare_1PassengerShareForWorkTours = 0.7
PaidRideshare_2PassengerShareForWorkTours = 0.2
PaidRideshare_AverageNumberFor3plusPassengerWorkTours = 4.0
        
PaidRideshare_1PassengerShareForSchoolTours = 0.5
PaidRideshare_2PassengerShareForSchoolTours = 0.3
PaidRideshare_AverageNumberFor3plusPassengerSchoolTours = 4.0

PaidRideshare_1PassengerShareForEscortTours = 0.1
PaidRideshare_2PassengerShareForEscortTours = 0.4
PaidRideshare_AverageNumberFor3plusPassengerEscortTours = 3.3

PaidRideshare_1PassengerShareForOtherTours  = 0.45
PaidRideshare_2PassengerShareForOtherTours = 0.35
PaidRideshare_AverageNumberFor3plusPassengerOtherTours = 4.25

Note that when this option is turned on, then the following configuration settings are overridden and not used:
 PaidRideshare_AvergeNumberOfPassengersForWorkTours
 PaidRideshare_AvergeNumberOfPassengersForSchoolTours
 PaidRideshare_AvergeNumberOfPassengersForEscortTours 
 PaidRideshare_AvergeNumberOfPassengersForOtherTours

**Comment by mabcal** [comment]
The way this option was implemented is somewhat different and simpler than in the previous comment.   It changes the DORP output field rather than the MODE output field, and, since it is meant for use with static assignment, it doesn't require specifying which passenger is the "main passenger", so it doesn't require input on the average number of passengers for 3+ passenger trips (although that will be needed for the external script that converts the DaySim trip list to vehicle-trip matrices). 

The up-to-date documentation is:
The "mode" field on the trip records is left as is, mode 9 = paid rideshare.  If this option is used and mode=9, then the "dorp" field on the output record has the following codes:

11 = paid rideshare, non-AV, 1 passenger, plus the driver
12 = paid rideshare, non-AV, 2 passengers, plus the driver
13 = paid rideshare, non-AV, 3+ passengers, plus the driver
21 = paid rideshare, AV, 1 passenger
22 = paid rideshare, AV, 2 passengers
23 = paid rideshare, AV, 3+ passengers

The option is turned on by setting.....
PaidRideshare_OutputNumberOfPassengersOnTripRecord = true

If it is turned on, DaySim expects the following 8 inputs below. For each of 4 tour purposes, there is the share of TNC trips that are 1 passenger and 2 passenger. The share that are 3+ passenger is then calculated as 1 - those 2 shares.  The representative values below were obtained by analyzing the TNC trips from the SANDAG survey and from the NHTS Bay Area trips.

PaidRideshare_1PassengerShareForWorkTours = 0.7
PaidRideshare_2PassengerShareForWorkTours = 0.2

PaidRideshare_1PassengerShareForSchoolTours = 0.5
PaidRideshare_2PassengerShareForSchoolTours = 0.3

PaidRideshare_1PassengerShareForEscortTours = 0.1
PaidRideshare_2PassengerShareForEscortTours = 0.4

PaidRideshare_1PassengerShareForOtherTours = 0.45
PaidRideshare_2PassengerShareForOtherTours = 0.35

Note that when this option is turned on, then the following configuration settings are overridden and not used:
PaidRideshare_AvergeNumberOfPassengersForWorkTours
PaidRideshare_AvergeNumberOfPassengersForSchoolTours
PaidRideshare_AvergeNumberOfPassengersForEscortTours
PaidRideshare_AvergeNumberOfPassengersForOtherTours

**Comment by bstabler** [comment]
@mabcal to update documentation as well - https://github.com/RSGInc/Daysim/wiki#users-guide

**Comment by bstabler** [comment]
See https://github.com/RSGInc/DaySim/wiki/docs/Documentation%20of%20DaySim%20changes%20to%20handle%20AVs%20and%20paid%20ride%20share%20mode.docx
