### ISSUE TITLE
Option to use AV skims by occupancy

### ISSUE THREAD

**Issue by mabcal** [RSGInc/DaySim#154]
If the configuration line
useAVSkimsByOccupancy = true
is included, then the modes
"av1", "av2" and "av3" can be used in the roster file to allow using different skims for the Sov, Hov2, and Hov3+ modes for private vehicles that are AVs (instead of using just "av")

Note that the Paid rideshare mode occupancy is only set on output, but is not yet set in the mode choice model itself, so the Paid rideshare mode will always use the hov2 skims by default (or the av2 skims if useAVSkimsByOccupancy and AV_PaidRideShareModeUsesAVs are both set to True).  

However, there are two new user configuration settings to allow the user more flexibility in which skims are used for the Paid Rideshare mode:

PaidRideshare_UseSOVSkims
If this is set to true, the Paid rideshare mode will use the sov skims from the roster (or the av1 skims if useAVSkimsByOccupancy and AV_PaidRideShareModeUsesAVs are both set to True). 

PaidRideshare_UseHOV3Skims
If this is set to true, the Paid rideshare mode will use the hov3 skims from the roster (or the av3 skims if useAVSkimsByOccupancy and AV_PaidRideShareModeUsesAVs are both set to True).

**Comment by mabcal** [comment]
Correction to the previous comment, the correct configuration setting name is...
AV_UseSeparateAVSkimMatricesByOccupancy = true

This overrides the setting
AV_UseSeparateAVSkimMatrices = true

If this is used, the roster-combinations.csv file should be updated to include the av1, av2 and av3 columns, as below

# | walk | bike | sov | hov2 | hov3 | transit | park-and-ride | school-bus | av1 | av2 | av3
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
full-network | TRUE | TRUE | TRUE | TRUE | TRUE | FALSE | FALSE | FALSE | TRUE | TRUE | TRUE
no-tolls | FALSE | FALSE | TRUE | TRUE | TRUE | FALSE | FALSE | FALSE | TRUE | TRUE | TRUE
local-bus | FALSE | FALSE | FALSE | FALSE | FALSE | TRUE | TRUE | FALSE | FALSE | FALSE | FALSE

**Comment by bstabler** [comment]
@mabcal to update documentation as well - https://github.com/RSGInc/Daysim/wiki#users-guide

**Comment by bstabler** [comment]
See https://github.com/RSGInc/DaySim/wiki/docs/Documentation%20of%20DaySim%20changes%20to%20handle%20AVs%20and%20paid%20ride%20share%20mode.docx
