### ISSUE TITLE
inconsistent time format - output files versus input estimation files

### ISSUE THREAD

**Issue by bstabler** [RSGInc/DaySim#158]
output file times are in minutes past midnight whereas input estimation file times are in hour*100+minute format.  We should make them consistent and add a backwards compatibility switch.

**Comment by bstabler** [comment]
updated documentation - https://github.com/RSGInc/DaySim/wiki/docs/Daysim%20Input%20Data%20File%20Documentation.docx

**Comment by mabcal** [comment]
Adding a new configuration switch
InputFileTimesAlreadyInMinutesPastMidnight

If this is included and set to true, RawConverter won't do the conversion from HHMM to MAM on input of the tour and trip files.
Eventually, that should probably be the default, but right now leaving HHMM as the default for backwards compatibility.
