### ISSUE TITLE
DaySim assumes US culture number format separator in some spots

### ISSUE THREAD

**Issue by bstabler** [RSGInc/DaySim#164]
See [here](https://stackoverflow.com/questions/24785689/trying-to-set-the-decimal-separator-for-the-current-language-getting-instance) for more info.  We should probably check the current culture of the Windows install at program startup and throw an exception if not en-US.  This was discovered because we tried running DaySim on a Danish computer.  Many Danish computers are set to use US number format separator (i.e. a comma instead of a period) so this is an usual situation, but it nevertheless is one we want to avoid.

**Comment by bstabler** [comment]
@PeterVermont - please check for US number format separator at startup and throw an exception if not true.  We ran into this issue when trying to run DaySim on a new Danish laptop that needed to be changed to use US number format separator.

**Comment by mabcal** [comment]
DaySim requires using a period, not a comma.

**Comment by PeterVermont** [comment]
Doh!
