### ISSUE TITLE
Remaining Actum specific code

### ISSUE THREAD

**Issue by PeterVermont** [RSGInc/DaySim#175]
This is a placeholder for a bunch of Actum differences in the code.

Just for completeness I will mention that the biggest area of difference is all of the Actum specific code which includes 'Actum' as part of the namespace.  There are whole folders and subfolders of this under ChoiceModels and DomainModels. In addition, Actum is the only user of the 'H' code including code that is not in the H namespace such as HTourDestinationModeTime, HTourModeTime, and HTripTime.

Additionally there is PathTypeModel_Actum which is in the Copenhagen separate project and which gets loaded via the customization code mechanism.

In addition to all of the above there are several places documented in the issues with the 'actum-integration' label.

Lastly there are little bits of code which did not seem deserving of separate issues each but which I would like people to say whether they make sense to remain as they are:
![image](https://user-images.githubusercontent.com/889233/46974671-b0835600-d092-11e8-8ff8-ba88bdeb3acb.png)

AND

![image](https://user-images.githubusercontent.com/889233/46974733-dc064080-d092-11e8-9de3-fc532647210e.png)

AND

![image](https://user-images.githubusercontent.com/889233/46974853-1ec81880-d093-11e8-9869-060734321b07.png)

AND

![image](https://user-images.githubusercontent.com/889233/46974891-38696000-d093-11e8-809d-1067e088ee4c.png)

AND

![image](https://user-images.githubusercontent.com/889233/46974917-4c14c680-d093-11e8-852f-c799461e5f06.png)

AND

![image](https://user-images.githubusercontent.com/889233/46974946-6058c380-d093-11e8-8513-ad50657016e3.png)

AND

![image](https://user-images.githubusercontent.com/889233/46975004-81211900-d093-11e8-8822-43c54e8d0dd0.png)

**Comment by bstabler** [comment]
We discussed these issues and made the following decisions:
  - ChoiceModels and DomainModels - we're going to keep a separate set of Actum ones
  - H code - we're keeping H but moving anything "H" into H for clearer organization
  - PathTypeModel_Actum - we'll try to move back to DaySim and drop the Copenhagen.dll, but if too difficult, we won't do it
  - StopAreaIsEnabled - Actum always has StopAreaIsEnabled so can remove duplicate check
  - Run method - keep as is
  - nearest_stoparea_id and all others - keep as is
  - calculate short distances in ParcelWrapper (not included above) - replace 'doNewCorrections' with DataType=='Actum', remove and re-run to see if not needed, and if so, remove.  If so, keep.
