### ISSUE TITLE
omx reader should use lookup if present

### ISSUE THREAD

**Issue by bstabler** [RSGInc/DaySim#207]
#186

**Comment by bstabler** [comment]
done

**Comment by YanmeiOu** [comment]
Hi Ben,

We’re using OMX reader. I’m trying to access how this fix would affect our model results, and if we need to download and use this updated version of DAYSIM. We’re in the middle of 2020 MTP/SCS scenario testing. Any change of model result will have big impact to our process.

Thanks,

Yanmei

**Comment by bstabler** [comment]
The existing models that use OMX, such as SACOG, have the same results as before.  We added support for reading OMX zone lookups, which are not used by SACOG (and most Cube models since zone numbers are sequential).
