### ISSUE TITLE
Get latest application version to also run in estimation mode

### ISSUE THREAD

**Issue by mabcal** [RSGInc/DaySim#269]

**Comment by mabcal** [comment]
This works.  Also need to add new trip file fields to survey data file to get it to work.

**Comment by bstabler** [comment]
@mabcal for Copenhagen (compass) correct?

**Comment by mabcal** [comment]
Right

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mabcal** [comment]
This is for Compass only.
