### ISSUE TITLE
For Copenhagen- changes to Auto Ownership model, plus park and ride lot capacity size term

### ISSUE THREAD

**Issue by mabcal** [RSGInc/DaySim#288]
Copied over the changes that Goran made to the AutoOwnershipModel.cs

Added a new configuration parameter 
COMPASS_AutoParkAndRideLotCapacitySizeWeight
with the default value 1.0.  This is a feature copied over from the main version of DaySim, and adds the log of park and ride lot capacity into the utility in the park and ride lot choice in PathTypeModel_Actum. This seems to work will where it has been tried, and makes the use of shadow pricing for park and ride lots less necessary.   To turn this back off, you would need to add configuration line 
COMPASS_AutoParkAndRideLotCapacitySizeWeight=0

(Note: In the main DaySim version used by US clients, the name of the parameters is:
PathImpedance_ParkAndRideLotCapacitySizeWeight, and it has default value 0, so to have an effect it has to be included in the configuration file (with recommended value of 1.0).

**Comment by dong-bellevue** [comment]
Mark,
Can you explain in more details of this new park and ride weight? What kind change/improvement do we expect to see? Thanks.

Hu (City of Bellevue)

**Comment by mabcal** [comment]
It uses the log of park and ride lot capacity as a size variable in the lot choice, so demand will match capacity more closely, even before doing shadow pricing.  It also increases the utility of the park and ride mode in work tour mode choice, so using it may require some re-calibration of the mode choice model.
