### ISSUE TITLE
Coefficient #37 used twice in SchoolTourModeModel

### ISSUE THREAD

**Issue by stefancoe** [RSGInc/DaySim#296]
Starting at line 335:
alternative.AddUtilityTerm(37, twoPersonHouseholdFlag);
 alternative.AddUtilityTerm(37, onePersonHouseholdFlag);

**Comment by stefancoe** [comment]
It looks like onePersonHouseholdFlag should be 38.

**Comment by mabcal** [comment]
That is usually intentional, as a way of constraining two variables to have the same coefficient. If you're reestimating, you can try different coefficient numbers.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mabcal** [comment]
I’m pretty sure the model was estimated using 37 for both.

Coefficient 38 is used for onePersonHouseholdFlag in the HOV2 utility, and I would expect the coefficient to be different for HOV2 and HOV3, so please don’t change it to 38..

To reestimate allowing different coefficients for one and two person households for HOV3 and also keeping the code backwards-compatible so it doesn’t change the results of other models, just add another additive parameter 48 as below (which would be interpreted as the difference between one person and two person HH for HOV3.   Other implementations don’t use coefficient 48 in their F12 file, so it will have no effect.

          alternative.AddUtilityTerm(37, twoPersonHouseholdFlag);
          alternative.AddUtilityTerm(37, onePersonHouseholdFlag);
          alternative.AddUtilityTerm(48, onePersonHouseholdFlag);

Mark

**Comment by stefancoe** [comment]
Ok, thanks. I will leave it as is then.
