### ISSUE TITLE
How difficult to run in a new city?

### ISSUE THREAD

**Issue by dabreegster** [RSGInc/DaySim#302]
Hi,

I'm the developer of [A/B Street](https://github.com/dabreegster/abstreet/), a traffic simulator that lets the general public become more involved with influencing local transportation projects. The project needs people/activity/trip data as input; it currently uses Seattle's Soundcast model, built on DaySim. Recently groups in other cities are interested in using A/B Street, but we're having trouble finding equivalent demand models.

@jvolker and @tori-d have tracked down some relevant input for [Berlin](https://github.com/dabreegster/abstreet/issues/119), such as travel surveys, census, and bike counters. How hard would it be for them to start using DaySim? Skimming through your docs on [input data](https://github.com/RSGInc/DaySim/wiki/docs/Daysim%20Input%20Data%20File%20Documentation.docx), there are lots of things likely missing for Berlin. Is there a minimal set of files to get started?

Combing through Soundcast's documentation, I realize how much region-specific work it's taken. The groups I'm talking to don't have the resources to repeat this effort. But if there is a way to generate some initial results easily from DaySim, then all of A/B Street's existing integration with Soundcast could be leveraged. Individual people and trips can be visualized, and we've got tools for exploring aggregate patterns:

![commute](https://user-images.githubusercontent.com/1664407/88428388-9f0fc780-cda9-11ea-813b-4a498b9ce6b7.png)

Some of these might also be generally useful for DaySim developers to understand model output. I'd love to find some sort of collaboration where A/B Street helps with dataviz, and DaySim helps onboard cities with less data.

Thanks,
-Dustin

**Comment by bstabler** [comment]
Hi @dabreegster.  See my response to ActivitySim issue [#326](https://github.com/ActivitySim/activitysim/issues/326).  ActivitySim is scheduled to replace DaySim so any further efforts would be geared toward ActivitySim.  Thanks.

**Comment by dabreegster** [comment]
I didn't realize the same groups are working on this. Closing as a duplicate of the other issue.
